export const PODCAST_GENRES = [
	{ name: 'Arts', value: 'PODCASTSERIES_ARTS' },
	{ name: 'Arts - Books', value: 'PODCASTSERIES_ARTS_BOOKS' },
	{ name: 'Arts - Design', value: 'PODCASTSERIES_ARTS_DESIGN' },
	{ name: 'Arts - Fashion and Beauty', value: 'PODCASTSERIES_ARTS_FASHION_AND_BEAUTY' },
	{ name: 'Arts - Food', value: 'PODCASTSERIES_ARTS_FOOD' },
	{ name: 'Arts - Performing Arts', value: 'PODCASTSERIES_ARTS_PERFORMING_ARTS' },
	{ name: 'Arts - Visual Arts', value: 'PODCASTSERIES_ARTS_VISUAL_ARTS' },
	{ name: 'Business', value: 'PODCASTSERIES_BUSINESS' },
	{ name: 'Business - Careers', value: 'PODCASTSERIES_BUSINESS_CAREERS' },
	{ name: 'Business - Entrepreneurship', value: 'PODCASTSERIES_BUSINESS_ENTREPRENEURSHIP' },
	{ name: 'Business - Investing', value: 'PODCASTSERIES_BUSINESS_INVESTING' },
	{ name: 'Business - Management', value: 'PODCASTSERIES_BUSINESS_MANAGEMENT' },
	{ name: 'Business - Marketing', value: 'PODCASTSERIES_BUSINESS_MARKETING' },
	{ name: 'Business - Non Profit', value: 'PODCASTSERIES_BUSINESS_NON_PROFIT' },
	{ name: 'Comedy', value: 'PODCASTSERIES_COMEDY' },
	{ name: 'Comedy - Improv', value: 'PODCASTSERIES_COMEDY_IMPROV' },
	{ name: 'Comedy - Interviews', value: 'PODCASTSERIES_COMEDY_INTERVIEWS' },
	{ name: 'Comedy - Stand-Up', value: 'PODCASTSERIES_COMEDY_STANDUP' },
	{ name: 'Education', value: 'PODCASTSERIES_EDUCATION' },
	{ name: 'Education - Courses', value: 'PODCASTSERIES_EDUCATION_COURSES' },
	{ name: 'Education - How To', value: 'PODCASTSERIES_EDUCATION_HOW_TO' },
	{ name: 'Education - Language Learning', value: 'PODCASTSERIES_EDUCATION_LANGUAGE_LEARNING' },
	{ name: 'Education - Self Improvement', value: 'PODCASTSERIES_EDUCATION_SELF_IMPROVEMENT' },
	{ name: 'Fiction', value: 'PODCASTSERIES_FICTION' },
	{ name: 'Fiction - Comedy Fiction', value: 'PODCASTSERIES_FICTION_COMEDY_FICTION' },
	{ name: 'Fiction - Drama', value: 'PODCASTSERIES_FICTION_DRAMA' },
	{ name: 'Fiction - Science Fiction', value: 'PODCASTSERIES_FICTION_SCIENCE_FICTION' },
	{ name: 'Government', value: 'PODCASTSERIES_GOVERNMENT' },
	{ name: 'Health and Fitness', value: 'PODCASTSERIES_HEALTH_AND_FITNESS' },
	{ name: 'Health and Fitness - Alternative Health', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_ALTERNATIVE_HEALTH' },
	{ name: 'Health and Fitness - Fitness', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_FITNESS' },
	{ name: 'Health and Fitness - Medicine', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_MEDICINE' },
	{ name: 'Health and Fitness - Mental Health', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_MENTAL_HEALTH' },
	{ name: 'Health and Fitness - Nutrition', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_NUTRITION' },
	{ name: 'Health and Fitness - Sexuality', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_SEXUALITY' },
	{ name: 'History', value: 'PODCASTSERIES_HISTORY' },
	{ name: 'Kids and Family', value: 'PODCASTSERIES_KIDS_AND_FAMILY' },
	{ name: 'Kids and Family - Education for Kids', value: 'PODCASTSERIES_KIDS_AND_FAMILY_EDUCATION_FOR_KIDS' },
	{ name: 'Kids and Family - Parenting', value: 'PODCASTSERIES_KIDS_AND_FAMILY_PARENTING' },
	{ name: 'Kids and Family - Pets and Animals', value: 'PODCASTSERIES_KIDS_AND_FAMILY_PETS_AND_ANIMALS' },
	{ name: 'Kids and Family - Stories for Kids', value: 'PODCASTSERIES_KIDS_AND_FAMILY_STORIES_FOR_KIDS' },
	{ name: 'Leisure', value: 'PODCASTSERIES_LEISURE' },
	{ name: 'Leisure - Animation and Manga', value: 'PODCASTSERIES_LEISURE_ANIMATION_AND_MANGA' },
	{ name: 'Leisure - Automotive', value: 'PODCASTSERIES_LEISURE_AUTOMOTIVE' },
	{ name: 'Leisure - Aviation', value: 'PODCASTSERIES_LEISURE_AVIATION' },
	{ name: 'Leisure - Crafts', value: 'PODCASTSERIES_LEISURE_CRAFTS' },
	{ name: 'Leisure - Games', value: 'PODCASTSERIES_LEISURE_GAMES' },
	{ name: 'Leisure - Hobbies', value: 'PODCASTSERIES_LEISURE_HOBBIES' },
	{ name: 'Leisure - Home and Garden', value: 'PODCASTSERIES_LEISURE_HOME_AND_GARDEN' },
	{ name: 'Leisure - Video Games', value: 'PODCASTSERIES_LEISURE_VIDEO_GAMES' },
	{ name: 'Music', value: 'PODCASTSERIES_MUSIC' },
	{ name: 'Music - Commentary', value: 'PODCASTSERIES_MUSIC_COMMENTARY' },
	{ name: 'Music - History', value: 'PODCASTSERIES_MUSIC_HISTORY' },
	{ name: 'Music - Interviews', value: 'PODCASTSERIES_MUSIC_INTERVIEWS' },
	{ name: 'News', value: 'PODCASTSERIES_NEWS' },
	{ name: 'News - Business', value: 'PODCASTSERIES_NEWS_BUSINESS' },
	{ name: 'News - Commentary', value: 'PODCASTSERIES_NEWS_COMMENTARY' },
	{ name: 'News - Daily News', value: 'PODCASTSERIES_NEWS_DAILY_NEWS' },
	{ name: 'News - Entertainment', value: 'PODCASTSERIES_NEWS_ENTERTAINMENT' },
	{ name: 'News - Politics', value: 'PODCASTSERIES_NEWS_POLITICS' },
	{ name: 'News - Sports', value: 'PODCASTSERIES_NEWS_SPORTS' },
	{ name: 'News - Tech', value: 'PODCASTSERIES_NEWS_TECH' },
	{ name: 'Religion and Spirituality', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY' },
	{ name: 'Religion and Spirituality - Buddhism', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_BUDDHISM' },
	{ name: 'Religion and Spirituality - Christianity', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_CHRISTIANITY' },
	{ name: 'Religion and Spirituality - Hinduism', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_HINDUISM' },
	{ name: 'Religion and Spirituality - Islam', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_ISLAM' },
	{ name: 'Religion and Spirituality - Judaism', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_JUDAISM' },
	{ name: 'Religion and Spirituality - Religion', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_RELIGION' },
	{ name: 'Religion and Spirituality - Spirituality', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_SPIRITUALITY' },
	{ name: 'Science', value: 'PODCASTSERIES_SCIENCE' },
	{ name: 'Science - Astronomy', value: 'PODCASTSERIES_SCIENCE_ASTRONOMY' },
	{ name: 'Science - Chemistry', value: 'PODCASTSERIES_SCIENCE_CHEMISTRY' },
	{ name: 'Science - Earth Sciences', value: 'PODCASTSERIES_SCIENCE_EARTH_SCIENCES' },
	{ name: 'Science - Life Sciences', value: 'PODCASTSERIES_SCIENCE_LIFE_SCIENCES' },
	{ name: 'Science - Mathematics', value: 'PODCASTSERIES_SCIENCE_MATHEMATICS' },
	{ name: 'Science - Natural Sciences', value: 'PODCASTSERIES_SCIENCE_NATURAL_SCIENCES' },
	{ name: 'Science - Nature', value: 'PODCASTSERIES_SCIENCE_NATURE' },
	{ name: 'Science - Physics', value: 'PODCASTSERIES_SCIENCE_PHYSICS' },
	{ name: 'Science - Social Sciences', value: 'PODCASTSERIES_SCIENCE_SOCIAL_SCIENCES' },
	{ name: 'Society and Culture', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE' },
	{ name: 'Society and Culture - Documentary', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_DOCUMENTARY' },
	{ name: 'Society and Culture - Personal Journals', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_PERSONAL_JOURNALS' },
	{ name: 'Society and Culture - Philosophy', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_PHILOSOPHY' },
	{ name: 'Society and Culture - Places and Travel', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_PLACES_AND_TRAVEL' },
	{ name: 'Society and Culture - Relationships', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_RELATIONSHIPS' },
	{ name: 'Sports', value: 'PODCASTSERIES_SPORTS' },
	{ name: 'Sports - Baseball', value: 'PODCASTSERIES_SPORTS_BASEBALL' },
	{ name: 'Sports - Basketball', value: 'PODCASTSERIES_SPORTS_BASKETBALL' },
	{ name: 'Sports - Cricket', value: 'PODCASTSERIES_SPORTS_CRICKET' },
	{ name: 'Sports - Fantasy Sports', value: 'PODCASTSERIES_SPORTS_FANTASY_SPORTS' },
	{ name: 'Sports - Football', value: 'PODCASTSERIES_SPORTS_FOOTBALL' },
	{ name: 'Sports - Golf', value: 'PODCASTSERIES_SPORTS_GOLF' },
	{ name: 'Sports - Hockey', value: 'PODCASTSERIES_SPORTS_HOCKEY' },
	{ name: 'Sports - Rugby', value: 'PODCASTSERIES_SPORTS_RUGBY' },
	{ name: 'Sports - Running', value: 'PODCASTSERIES_SPORTS_RUNNING' },
	{ name: 'Sports - Soccer', value: 'PODCASTSERIES_SPORTS_SOCCER' },
	{ name: 'Sports - Swimming', value: 'PODCASTSERIES_SPORTS_SWIMMING' },
	{ name: 'Sports - Tennis', value: 'PODCASTSERIES_SPORTS_TENNIS' },
	{ name: 'Sports - Volleyball', value: 'PODCASTSERIES_SPORTS_VOLLEYBALL' },
	{ name: 'Sports - Wilderness', value: 'PODCASTSERIES_SPORTS_WILDERNESS' },
	{ name: 'Sports - Wrestling', value: 'PODCASTSERIES_SPORTS_WRESTLING' },
	{ name: 'Technology', value: 'PODCASTSERIES_TECHNOLOGY' },
	{ name: 'True Crime', value: 'PODCASTSERIES_TRUE_CRIME' },
	{ name: 'TV and Film', value: 'PODCASTSERIES_TV_AND_FILM' },
	{ name: 'TV and Film - After Shows', value: 'PODCASTSERIES_TV_AND_FILM_AFTER_SHOWS' },
	{ name: 'TV and Film - Film Reviews', value: 'PODCASTSERIES_TV_AND_FILM_FILM_REVIEWS' },
	{ name: 'TV and Film - History', value: 'PODCASTSERIES_TV_AND_FILM_HISTORY' },
	{ name: 'TV and Film - Interviews', value: 'PODCASTSERIES_TV_AND_FILM_INTERVIEWS' },
	{ name: 'TV and Film - TV Reviews', value: 'PODCASTSERIES_TV_AND_FILM_TV_REVIEWS' },
];

export const COUNTRIES = [
	{ name: 'Afghanistan', value: 'AFGHANISTAN' },
	{ name: 'Åland Islands', value: 'ALAND_ISLANDS' },
	{ name: 'Albania', value: 'ALBANIA' },
	{ name: 'Algeria', value: 'ALGERIA' },
	{ name: 'American Samoa', value: 'AMERICAN_SAMOA' },
	{ name: 'Andorra', value: 'ANDORRA' },
	{ name: 'Angola', value: 'ANGOLA' },
	{ name: 'Anguilla', value: 'ANGUILLA' },
	{ name: 'Antarctica', value: 'ANTARCTICA' },
	{ name: 'Antigua and Barbuda', value: 'ANTIGUA_AND_BARBUDA' },
	{ name: 'Argentina', value: 'ARGENTINA' },
	{ name: 'Armenia', value: 'ARMENIA' },
	{ name: 'Aruba', value: 'ARUBA' },
	{ name: 'Australia', value: 'AUSTRALIA' },
	{ name: 'Austria', value: 'AUSTRIA' },
	{ name: 'Azerbaijan', value: 'AZERBAIJAN' },
	{ name: 'Bahamas', value: 'BAHAMAS' },
	{ name: 'Bahrain', value: 'BAHRAIN' },
	{ name: 'Bangladesh', value: 'BANGLADESH' },
	{ name: 'Barbados', value: 'BARBADOS' },
	{ name: 'Belarus', value: 'BELARUS' },
	{ name: 'Belgium', value: 'BELGIUM' },
	{ name: 'Belize', value: 'BELIZE' },
	{ name: 'Benin', value: 'BENIN' },
	{ name: 'Bermuda', value: 'BERMUDA' },
	{ name: 'Bhutan', value: 'BHUTAN' },
	{ name: 'Bolivia', value: 'BOLIVIA_PLURINATIONAL_STATE_OF' },
	{ name: 'Bonaire, Sint Eustatius and Saba', value: 'BONAIRE_SINT_EUSTATIUS_AND_SABA' },
	{ name: 'Bosnia and Herzegovina', value: 'BOSNIA_AND_HERZEGOVINA' },
	{ name: 'Botswana', value: 'BOTSWANA' },
	{ name: 'Bouvet Island', value: 'BOUVET_ISLAND' },
	{ name: 'Brazil', value: 'BRAZIL' },
	{ name: 'British Indian Ocean Territory', value: 'BRITISH_INDIAN_OCEAN_TERRITORY_THE' },
	{ name: 'Brunei Darussalam', value: 'BRUNEI_DARUSSALAM' },
	{ name: 'Bulgaria', value: 'BULGARIA' },
	{ name: 'Burkina Faso', value: 'BURKINA_FASO' },
	{ name: 'Burundi', value: 'BURUNDI' },
	{ name: 'Cabo Verde', value: 'CABO_VERDE' },
	{ name: 'Cambodia', value: 'CAMBODIA' },
	{ name: 'Cameroon', value: 'CAMEROON' },
	{ name: 'Canada', value: 'CANADA' },
	{ name: 'Cayman Islands', value: 'CAYMAN_ISLANDS' },
	{ name: 'Central African Republic', value: 'CENTRAL_AFRICAN_REPUBLIC' },
	{ name: 'Chad', value: 'CHAD' },
	{ name: 'Chile', value: 'CHILE' },
	{ name: 'China', value: 'CHINA' },
	{ name: 'Christmas Island', value: 'CHRISTMAS_ISLAND' },
	{ name: 'Cocos (Keeling) Islands', value: 'COCOS_KEELING_ISLANDS' },
	{ name: 'Colombia', value: 'COLOMBIA' },
	{ name: 'Comoros', value: 'COMOROS' },
	{ name: 'Congo', value: 'CONGO' },
	{ name: 'Congo (Democratic Republic)', value: 'CONGO_THE_DEMOCRATIC_REPUBLIC_OF' },
	{ name: 'Cook Islands', value: 'COOK_ISLANDS' },
	{ name: 'Costa Rica', value: 'COSTA_RICA' },
	{ name: "Côte d'Ivoire", value: 'COTE_D_IVOIRE' },
	{ name: 'Croatia', value: 'CROATIA' },
	{ name: 'Cuba', value: 'CUBA' },
	{ name: 'Curaçao', value: 'CURACAO' },
	{ name: 'Cyprus', value: 'CYPRUS' },
	{ name: 'Czechia', value: 'CZECHIA' },
	{ name: 'Denmark', value: 'DENMARK' },
	{ name: 'Djibouti', value: 'DJIBOUTI' },
	{ name: 'Dominica', value: 'DOMINICA' },
	{ name: 'Dominican Republic', value: 'DOMINICAN_REPUBLIC' },
	{ name: 'Ecuador', value: 'ECUADOR' },
	{ name: 'Egypt', value: 'EGYPT' },
	{ name: 'El Salvador', value: 'EL_SALVADOR' },
	{ name: 'Equatorial Guinea', value: 'EQUATORIAL_GUINEA' },
	{ name: 'Eritrea', value: 'ERITREA' },
	{ name: 'Estonia', value: 'ESTONIA' },
	{ name: 'Eswatini', value: 'ESWATINI' },
	{ name: 'Ethiopia', value: 'ETHIOPIA' },
	{ name: 'Falkland Islands (Malvinas)', value: 'FALKLAND_ISLANDS_THE_MALVINAS' },
	{ name: 'Faroe Islands', value: 'FAROE_ISLANDS' },
	{ name: 'Fiji', value: 'FIJI' },
	{ name: 'Finland', value: 'FINLAND' },
	{ name: 'France', value: 'FRANCE' },
	{ name: 'French Guiana', value: 'FRENCH_GUIANA' },
	{ name: 'French Polynesia', value: 'FRENCH_POLYNESIA' },
	{ name: 'French Southern Territories', value: 'FRENCH_SOUTHERN_TERRITORIES' },
	{ name: 'Gabon', value: 'GABON' },
	{ name: 'Gambia', value: 'GAMBIA' },
	{ name: 'Georgia', value: 'GEORGIA' },
	{ name: 'Germany', value: 'GERMANY' },
	{ name: 'Ghana', value: 'GHANA' },
	{ name: 'Gibraltar', value: 'GIBRALTAR' },
	{ name: 'Greece', value: 'GREECE' },
	{ name: 'Greenland', value: 'GREENLAND' },
	{ name: 'Grenada', value: 'GRENADA' },
	{ name: 'Guadeloupe', value: 'GUADELOUPE' },
	{ name: 'Guam', value: 'GUAM' },
	{ name: 'Guatemala', value: 'GUATEMALA' },
	{ name: 'Guernsey', value: 'GUERNSEY' },
	{ name: 'Guinea', value: 'GUINEA' },
	{ name: 'Guinea-Bissau', value: 'GUINEA_BISSAU' },
	{ name: 'Guyana', value: 'GUYANA' },
	{ name: 'Haiti', value: 'HAITI' },
	{ name: 'Heard Island and McDonald Islands', value: 'HEARD_ISLAND_AND_MCDONALD_ISLANDS' },
	{ name: 'Holy See', value: 'HOLY_SEE' },
	{ name: 'Honduras', value: 'HONDURAS' },
	{ name: 'Hong Kong', value: 'HONG_KONG' },
	{ name: 'Hungary', value: 'HUNGARY' },
	{ name: 'Iceland', value: 'ICELAND' },
	{ name: 'India', value: 'INDIA' },
	{ name: 'Indonesia', value: 'INDONESIA' },
	{ name: 'Iran', value: 'IRAN' },
	{ name: 'Iraq', value: 'IRAQ' },
	{ name: 'Ireland', value: 'IRELAND' },
	{ name: 'Isle of Man', value: 'ISLE_OF_MAN' },
	{ name: 'Israel', value: 'ISRAEL' },
	{ name: 'Italy', value: 'ITALY' },
	{ name: 'Jamaica', value: 'JAMAICA' },
	{ name: 'Japan', value: 'JAPAN' },
	{ name: 'Jersey', value: 'JERSEY' },
	{ name: 'Jordan', value: 'JORDAN' },
	{ name: 'Kazakhstan', value: 'KAZAKHSTAN' },
	{ name: 'Kenya', value: 'KENYA' },
	{ name: 'Kiribati', value: 'KIRIBATI' },
	{ name: 'Korea (North)', value: 'KOREA_NORTH' },
	{ name: 'Korea (South)', value: 'KOREA_SOUTH' },
	{ name: 'Kuwait', value: 'KUWAIT' },
	{ name: 'Kyrgyzstan', value: 'KYRGYZSTAN' },
	{ name: 'Lao People\'s Democratic Republic', value: 'LAO_PEOPLES_DEMOCRATIC_REPUBLIC_THE' },
	{ name: 'Latvia', value: 'LATVIA' },
	{ name: 'Lebanon', value: 'LEBANON' },
	{ name: 'Lesotho', value: 'LESOTHO' },
	{ name: 'Liberia', value: 'LIBERIA' },
	{ name: 'Libya', value: 'LIBYA' },
	{ name: 'Liechtenstein', value: 'LIECHTENSTEIN' },
	{ name: 'Lithuania', value: 'LITHUANIA' },
	{ name: 'Luxembourg', value: 'LUXEMBOURG' },
	{ name: 'Macao', value: 'MACAO' },
	{ name: 'Madagascar', value: 'MADAGASCAR' },
	{ name: 'Malawi', value: 'MALAWI' },
	{ name: 'Malaysia', value: 'MALAYSIA' },
	{ name: 'Maldives', value: 'MALDIVES' },
	{ name: 'Mali', value: 'MALI' },
	{ name: 'Malta', value: 'MALTA' },
	{ name: 'Marshall Islands', value: 'MARSHALL_ISLANDS' },
	{ name: 'Martinique', value: 'MARTINIQUE' },
	{ name: 'Mauritania', value: 'MAURITANIA' },
	{ name: 'Mauritius', value: 'MAURITIUS' },
	{ name: 'Mayotte', value: 'MAYOTTE' },
	{ name: 'Mexico', value: 'MEXICO' },
	{ name: 'Micronesia', value: 'MICRONESIA_FEDERATED_STATES' },
	{ name: 'Minor Outlying Islands (US)', value: 'MINOR_OUTLYING_ISLANDS_US' },
	{ name: 'Moldova', value: 'MOLDOVA_THE_REPUBLIC' },
	{ name: 'Monaco', value: 'MONACO' },
	{ name: 'Mongolia', value: 'MONGOLIA' },
	{ name: 'Montenegro', value: 'MONTENEGRO' },
	{ name: 'Montserrat', value: 'MONTSERRAT' },
	{ name: 'Morocco', value: 'MOROCCO' },
	{ name: 'Mozambique', value: 'MOZAMBIQUE' },
	{ name: 'Myanmar', value: 'MYANMAR' },
	{ name: 'Namibia', value: 'NAMIBIA' },
	{ name: 'Nauru', value: 'NAURU' },
	{ name: 'Nepal', value: 'NEPAL' },
	{ name: 'Netherlands', value: 'NETHERLANDS' },
	{ name: 'New Caledonia', value: 'NEW_CALEDONIA' },
	{ name: 'New Zealand', value: 'NEW_ZEALAND' },
	{ name: 'Nicaragua', value: 'NICARAGUA' },
	{ name: 'Niger', value: 'NIGER' },
	{ name: 'Nigeria', value: 'NIGERIA' },
	{ name: 'Niue', value: 'NIUE' },
	{ name: 'None', value: '' },
	{ name: 'Norfolk Island', value: 'NORFOLK_ISLAND' },
	{ name: 'North Macedonia', value: 'NORTH_MACEDONIA' },
	{ name: 'Northern Mariana Islands', value: 'NORTHERN_MARIANA_ISLANDS' },
	{ name: 'Norway', value: 'NORWAY' },
	{ name: 'Oman', value: 'OMAN' },
	{ name: 'Pakistan', value: 'PAKISTAN' },
	{ name: 'Palau', value: 'PALAU' },
	{ name: 'Palestine, State Of', value: 'PALESTINE_STATE' },
	{ name: 'Panama', value: 'PANAMA' },
	{ name: 'Papua New Guinea', value: 'PAPUA_NEW_GUINEA' },
	{ name: 'Paraguay', value: 'PARAGUAY' },
	{ name: 'Peru', value: 'PERU' },
	{ name: 'Philippines', value: 'PHILIPPINES' },
	{ name: 'Pitcairn', value: 'PITCAIRN' },
	{ name: 'Poland', value: 'POLAND' },
	{ name: 'Portugal', value: 'PORTUGAL' },
	{ name: 'Puerto Rico', value: 'PUERTO_RICO' },
	{ name: 'Qatar', value: 'QATAR' },
	{ name: 'Réunion', value: 'REUNION' },
	{ name: 'Romania', value: 'ROMANIA' },
	{ name: 'Russia', value: 'RUSSIA' },
	{ name: 'Rwanda', value: 'RWANDA' },
	{ name: 'Saint Barthélemy', value: 'SAINT_BARTHELEMY' },
	{ name: 'Saint Helena, Ascension and Tristan Da Cunha', value: 'SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA' },
	{ name: 'Saint Kitts and Nevis', value: 'SAINT_KITTS_AND_NEVIS' },
	{ name: 'Saint Lucia', value: 'SAINT_LUCIA' },
	{ name: 'Saint Martin (French Part)', value: 'SAINT_MARTIN_FRENCH_PART' },
	{ name: 'Saint Pierre and Miquelon', value: 'SAINT_PIERRE_AND_MIQUELON' },
	{ name: 'Saint Vincent and the Grenadines', value: 'SAINT_VINCENT_AND_THE_GRENADINES' },
	{ name: 'Samoa', value: 'SAMOA' },
	{ name: 'San Marino', value: 'SAN_MARINO' },
	{ name: 'Sao Tome and Principe', value: 'SAO_TOME_AND_PRINCIPE' },
	{ name: 'Saudi Arabia', value: 'SAUDI_ARABIA' },
	{ name: 'Senegal', value: 'SENEGAL' },
	{ name: 'Serbia', value: 'SERBIA' },
	{ name: 'Seychelles', value: 'SEYCHELLES' },
	{ name: 'Sierra Leone', value: 'SIERRA_LEONE' },
	{ name: 'Singapore', value: 'SINGAPORE' },
	{ name: 'Sint Maarten (Dutch Part)', value: 'SINT_MAARTEN_DUTCH_PART' },
	{ name: 'Slovakia', value: 'SLOVAKIA' },
	{ name: 'Slovenia', value: 'SLOVENIA' },
	{ name: 'Solomon Islands', value: 'SOLOMON_ISLANDS' },
	{ name: 'Somalia', value: 'SOMALIA' },
	{ name: 'South Africa', value: 'SOUTH_AFRICA' },
	{ name: 'South Georgia and the South Sandwich Islands', value: 'SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS' },
	{ name: 'South Sudan', value: 'SOUTH_SUDAN' },
	{ name: 'Spain', value: 'SPAIN' },
	{ name: 'Sri Lanka', value: 'SRI_LANKA' },
	{ name: 'Sudan', value: 'SUDAN' },
	{ name: 'Suriname', value: 'SURINAME' },
	{ name: 'Svalbard and Jan Mayen', value: 'SVALBARD_AND_JAN_MAYEN' },
	{ name: 'Sweden', value: 'SWEDEN' },
	{ name: 'Switzerland', value: 'SWITZERLAND' },
	{ name: 'Syria', value: 'SYRIA' },
	{ name: 'Taiwan', value: 'TAIWAN' },
	{ name: 'Tajikistan', value: 'TAJIKISTAN' },
	{ name: 'Tanzania', value: 'TANZANIA' },
	{ name: 'Thailand', value: 'THAILAND' },
	{ name: 'Timor-Leste', value: 'TIMOR_LESTE' },
	{ name: 'Togo', value: 'TOGO' },
	{ name: 'Tokelau', value: 'TOKELAU' },
	{ name: 'Tonga', value: 'TONGA' },
	{ name: 'Trinidad and Tobago', value: 'TRINIDAD_AND_TOBAGO' },
	{ name: 'Tunisia', value: 'TUNISIA' },
	{ name: 'Turkey', value: 'TURKEY' },
	{ name: 'Turkmenistan', value: 'TURKMENISTAN' },
	{ name: 'Turks and Caicos Islands', value: 'TURKS_AND_CAICOS_ISLANDS' },
	{ name: 'Tuvalu', value: 'TUVALU' },
	{ name: 'Uganda', value: 'UGANDA' },
	{ name: 'Ukraine', value: 'UKRAINE' },
	{ name: 'United Arab Emirates', value: 'UNITED_ARAB_EMIRATES' },
	{ name: 'United Kingdom', value: 'UNITED_KINGDOM' },
	{ name: 'United States', value: 'UNITED_STATES_OF_AMERICA' },
	{ name: 'Uruguay', value: 'URUGUAY' },
	{ name: 'Uzbekistan', value: 'UZBEKISTAN' },
	{ name: 'Vanuatu', value: 'VANUATU' },
	{ name: 'Venezuela', value: 'VENEZUELA' },
	{ name: 'Vietnam', value: 'VIETNAM' },
	{ name: 'Virgin Islands (British)', value: 'VIRGIN_ISLANDS_BRITISH' },
	{ name: 'Virgin Islands (U.S.)', value: 'VIRGIN_ISLANDS_US' },
	{ name: 'Wallis and Futuna', value: 'WALLIS_AND_FUTUNA' },
	{ name: 'Western Sahara', value: 'WESTERN_SAHARA' },
	{ name: 'Yemen', value: 'YEMEN' },
	{ name: 'Zambia', value: 'ZAMBIA' },
	{ name: 'Zimbabwe', value: 'ZIMBABWE' },
];