export const COUNTRIES = [
	{ name: 'Afghanistan', value: 'AFGHANISTAN' },
	{ name: 'Åland Islands', value: 'ALAND_ISLANDS' },
	{ name: 'Albania', value: 'ALBANIA' },
	{ name: 'Algeria', value: 'ALGERIA' },
	{ name: 'American Samoa', value: 'AMERICAN_SAMOA' },
	{ name: 'Andorra', value: 'ANDORRA' },
	{ name: 'Angola', value: 'ANGOLA' },
	{ name: 'Anguilla', value: 'ANGUILLA' },
	{ name: 'Antarctica', value: 'ANTARCTICA' },
	{ name: 'Antigua and Barbuda', value: 'ANTIGUA_AND_BARBUDA' },
	{ name: 'Argentina', value: 'ARGENTINA' },
	{ name: 'Armenia', value: 'ARMENIA' },
	{ name: 'Aruba', value: 'ARUBA' },
	{ name: 'Australia', value: 'AUSTRALIA' },
	{ name: 'Austria', value: 'AUSTRIA' },
	{ name: 'Azerbaijan', value: 'AZERBAIJAN' },
	{ name: 'Bahamas', value: 'BAHAMAS' },
	{ name: 'Bahrain', value: 'BAHRAIN' },
	{ name: 'Bangladesh', value: 'BANGLADESH' },
	{ name: 'Barbados', value: 'BARBADOS' },
	{ name: 'Belarus', value: 'BELARUS' },
	{ name: 'Belgium', value: 'BELGIUM' },
	{ name: 'Belize', value: 'BELIZE' },
	{ name: 'Benin', value: 'BENIN' },
	{ name: 'Bermuda', value: 'BERMUDA' },
	{ name: 'Bhutan', value: 'BHUTAN' },
	{ name: 'Bolivia', value: 'BOLIVIA_PLURINATIONAL_STATE_OF' },
	{ name: 'Bonaire, Sint Eustatius and Saba', value: 'BONAIRE_SINT_EUSTATIUS_AND_SABA' },
	{ name: 'Bosnia and Herzegovina', value: 'BOSNIA_AND_HERZEGOVINA' },
	{ name: 'Botswana', value: 'BOTSWANA' },
	{ name: 'Bouvet Island', value: 'BOUVET_ISLAND' },
	{ name: 'Brazil', value: 'BRAZIL' },
	{ name: 'British Indian Ocean Territory', value: 'BRITISH_INDIAN_OCEAN_TERRITORY_THE' },
	{ name: 'Brunei Darussalam', value: 'BRUNEI_DARUSSALAM' },
	{ name: 'Bulgaria', value: 'BULGARIA' },
	{ name: 'Burkina Faso', value: 'BURKINA_FASO' },
	{ name: 'Burundi', value: 'BURUNDI' },
	{ name: 'Cabo Verde', value: 'CABO_VERDE' },
	{ name: 'Cambodia', value: 'CAMBODIA' },
	{ name: 'Cameroon', value: 'CAMEROON' },
	{ name: 'Canada', value: 'CANADA' },
	{ name: 'Cayman Islands', value: 'CAYMAN_ISLANDS' },
	{ name: 'Central African Republic', value: 'CENTRAL_AFRICAN_REPUBLIC' },
	{ name: 'Chad', value: 'CHAD' },
	{ name: 'Chile', value: 'CHILE' },
	{ name: 'China', value: 'CHINA' },
	{ name: 'Christmas Island', value: 'CHRISTMAS_ISLAND' },
	{ name: 'Cocos (Keeling) Islands', value: 'COCOS_KEELING_ISLANDS' },
	{ name: 'Colombia', value: 'COLOMBIA' },
	{ name: 'Comoros', value: 'COMOROS' },
	{ name: 'Congo', value: 'CONGO' },
	{ name: 'Congo (Democratic Republic)', value: 'CONGO_THE_DEMOCRATIC_REPUBLIC_OF' },
	{ name: 'Cook Islands', value: 'COOK_ISLANDS' },
	{ name: 'Costa Rica', value: 'COSTA_RICA' },
	{ name: "Côte d'Ivoire", value: 'COTE_D_IVOIRE' },
	{ name: 'Croatia', value: 'CROATIA' },
	{ name: 'Cuba', value: 'CUBA' },
	{ name: 'Curaçao', value: 'CURACAO' },
	{ name: 'Cyprus', value: 'CYPRUS' },
	{ name: 'Czechia', value: 'CZECHIA' },
	{ name: 'Denmark', value: 'DENMARK' },
	{ name: 'Djibouti', value: 'DJIBOUTI' },
	{ name: 'Dominica', value: 'DOMINICA' },
	{ name: 'Dominican Republic', value: 'DOMINICAN_REPUBLIC' },
	{ name: 'Ecuador', value: 'ECUADOR' },
	{ name: 'Egypt', value: 'EGYPT' },
	{ name: 'El Salvador', value: 'EL_SALVADOR' },
	{ name: 'Equatorial Guinea', value: 'EQUATORIAL_GUINEA' },
	{ name: 'Eritrea', value: 'ERITREA' },
	{ name: 'Estonia', value: 'ESTONIA' },
	{ name: 'Eswatini', value: 'ESWATINI' },
	{ name: 'Ethiopia', value: 'ETHIOPIA' },
	{ name: 'Falkland Islands (Malvinas)', value: 'FALKLAND_ISLANDS_THE_MALVINAS' },
	{ name: 'Faroe Islands', value: 'FAROE_ISLANDS' },
	{ name: 'Fiji', value: 'FIJI' },
	{ name: 'Finland', value: 'FINLAND' },
	{ name: 'France', value: 'FRANCE' },
	{ name: 'French Guiana', value: 'FRENCH_GUIANA' },
	{ name: 'French Polynesia', value: 'FRENCH_POLYNESIA' },
	{ name: 'French Southern Territories', value: 'FRENCH_SOUTHERN_TERRITORIES' },
	{ name: 'Gabon', value: 'GABON' },
	{ name: 'Gambia', value: 'GAMBIA' },
	{ name: 'Georgia', value: 'GEORGIA' },
	{ name: 'Germany', value: 'GERMANY' },
	{ name: 'Ghana', value: 'GHANA' },
	{ name: 'Gibraltar', value: 'GIBRALTAR' },
	{ name: 'Greece', value: 'GREECE' },
	{ name: 'Greenland', value: 'GREENLAND' },
	{ name: 'Grenada', value: 'GRENADA' },
	{ name: 'Guadeloupe', value: 'GUADELOUPE' },
	{ name: 'Guam', value: 'GUAM' },
	{ name: 'Guatemala', value: 'GUATEMALA' },
	{ name: 'Guernsey', value: 'GUERNSEY' },
	{ name: 'Guinea', value: 'GUINEA' },
	{ name: 'Guinea-Bissau', value: 'GUINEA_BISSAU' },
	{ name: 'Guyana', value: 'GUYANA' },
	{ name: 'Haiti', value: 'HAITI' },
	{ name: 'Heard Island and McDonald Islands', value: 'HEARD_ISLAND_AND_MCDONALD_ISLANDS' },
	{ name: 'Holy See', value: 'HOLY_SEE' },
	{ name: 'Honduras', value: 'HONDURAS' },
	{ name: 'Hong Kong', value: 'HONG_KONG' },
	{ name: 'Hungary', value: 'HUNGARY' },
	{ name: 'Iceland', value: 'ICELAND' },
	{ name: 'India', value: 'INDIA' },
	{ name: 'Indonesia', value: 'INDONESIA' },
	{ name: 'Iran', value: 'IRAN' },
	{ name: 'Iraq', value: 'IRAQ' },
	{ name: 'Ireland', value: 'IRELAND' },
	{ name: 'Isle of Man', value: 'ISLE_OF_MAN' },
	{ name: 'Israel', value: 'ISRAEL' },
	{ name: 'Italy', value: 'ITALY' },
	{ name: 'Jamaica', value: 'JAMAICA' },
	{ name: 'Japan', value: 'JAPAN' },
	{ name: 'Jersey', value: 'JERSEY' },
	{ name: 'Jordan', value: 'JORDAN' },
	{ name: 'Kazakhstan', value: 'KAZAKHSTAN' },
	{ name: 'Kenya', value: 'KENYA' },
	{ name: 'Kiribati', value: 'KIRIBATI' },
	{ name: 'Korea (North)', value: 'KOREA_NORTH' },
	{ name: 'Korea (South)', value: 'KOREA_SOUTH' },
	{ name: 'Kuwait', value: 'KUWAIT' },
	{ name: 'Kyrgyzstan', value: 'KYRGYZSTAN' },
	{ name: "Lao People's Democratic Republic", value: 'LAO_PEOPLES_DEMOCRATIC_REPUBLIC_THE' },
	{ name: 'Latvia', value: 'LATVIA' },
	{ name: 'Lebanon', value: 'LEBANON' },
	{ name: 'Lesotho', value: 'LESOTHO' },
	{ name: 'Liberia', value: 'LIBERIA' },
	{ name: 'Libya', value: 'LIBYA' },
	{ name: 'Liechtenstein', value: 'LIECHTENSTEIN' },
	{ name: 'Lithuania', value: 'LITHUANIA' },
	{ name: 'Luxembourg', value: 'LUXEMBOURG' },
	{ name: 'Macao', value: 'MACAO' },
	{ name: 'Madagascar', value: 'MADAGASCAR' },
	{ name: 'Malawi', value: 'MALAWI' },
	{ name: 'Malaysia', value: 'MALAYSIA' },
	{ name: 'Maldives', value: 'MALDIVES' },
	{ name: 'Mali', value: 'MALI' },
	{ name: 'Malta', value: 'MALTA' },
	{ name: 'Marshall Islands', value: 'MARSHALL_ISLANDS' },
	{ name: 'Martinique', value: 'MARTINIQUE' },
	{ name: 'Mauritania', value: 'MAURITANIA' },
	{ name: 'Mauritius', value: 'MAURITIUS' },
	{ name: 'Mayotte', value: 'MAYOTTE' },
	{ name: 'Mexico', value: 'MEXICO' },
	{ name: 'Micronesia', value: 'MICRONESIA_FEDERATED_STATES' },
	{ name: 'Minor Outlying Islands (US)', value: 'MINOR_OUTLYING_ISLANDS_US' },
	{ name: 'Moldova', value: 'MOLDOVA_THE_REPUBLIC' },
	{ name: 'Monaco', value: 'MONACO' },
	{ name: 'Mongolia', value: 'MONGOLIA' },
	{ name: 'Montenegro', value: 'MONTENEGRO' },
	{ name: 'Montserrat', value: 'MONTSERRAT' },
	{ name: 'Morocco', value: 'MOROCCO' },
	{ name: 'Mozambique', value: 'MOZAMBIQUE' },
	{ name: 'Myanmar', value: 'MYANMAR' },
	{ name: 'Namibia', value: 'NAMIBIA' },
	{ name: 'Nauru', value: 'NAURU' },
	{ name: 'Nepal', value: 'NEPAL' },
	{ name: 'Netherlands', value: 'NETHERLANDS' },
	{ name: 'New Caledonia', value: 'NEW_CALEDONIA' },
	{ name: 'New Zealand', value: 'NEW_ZEALAND' },
	{ name: 'Nicaragua', value: 'NICARAGUA' },
	{ name: 'Niger', value: 'NIGER' },
	{ name: 'Nigeria', value: 'NIGERIA' },
	{ name: 'Niue', value: 'NIUE' },
	{ name: 'None', value: '' },
	{ name: 'Norfolk Island', value: 'NORFOLK_ISLAND' },
	{ name: 'North Macedonia', value: 'NORTH_MACEDONIA' },
	{ name: 'Northern Mariana Islands', value: 'NORTHERN_MARIANA_ISLANDS' },
	{ name: 'Norway', value: 'NORWAY' },
	{ name: 'Oman', value: 'OMAN' },
	{ name: 'Pakistan', value: 'PAKISTAN' },
	{ name: 'Palau', value: 'PALAU' },
	{ name: 'Palestine, State Of', value: 'PALESTINE_STATE' },
	{ name: 'Panama', value: 'PANAMA' },
	{ name: 'Papua New Guinea', value: 'PAPUA_NEW_GUINEA' },
	{ name: 'Paraguay', value: 'PARAGUAY' },
	{ name: 'Peru', value: 'PERU' },
	{ name: 'Philippines', value: 'PHILIPPINES' },
	{ name: 'Pitcairn', value: 'PITCAIRN' },
	{ name: 'Poland', value: 'POLAND' },
	{ name: 'Portugal', value: 'PORTUGAL' },
	{ name: 'Puerto Rico', value: 'PUERTO_RICO' },
	{ name: 'Qatar', value: 'QATAR' },
	{ name: 'Réunion', value: 'REUNION' },
	{ name: 'Romania', value: 'ROMANIA' },
	{ name: 'Russia', value: 'RUSSIA' },
	{ name: 'Rwanda', value: 'RWANDA' },
	{ name: 'Saint Barthélemy', value: 'SAINT_BARTHELEMY' },
	{ name: 'Saint Helena, Ascension and Tristan Da Cunha', value: 'SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA' },
	{ name: 'Saint Kitts and Nevis', value: 'SAINT_KITTS_AND_NEVIS' },
	{ name: 'Saint Lucia', value: 'SAINT_LUCIA' },
	{ name: 'Saint Martin (French Part)', value: 'SAINT_MARTIN_FRENCH_PART' },
	{ name: 'Saint Pierre and Miquelon', value: 'SAINT_PIERRE_AND_MIQUELON' },
	{ name: 'Saint Vincent and the Grenadines', value: 'SAINT_VINCENT_AND_THE_GRENADINES' },
	{ name: 'Samoa', value: 'SAMOA' },
	{ name: 'San Marino', value: 'SAN_MARINO' },
	{ name: 'Sao Tome and Principe', value: 'SAO_TOME_AND_PRINCIPE' },
	{ name: 'Saudi Arabia', value: 'SAUDI_ARABIA' },
	{ name: 'Senegal', value: 'SENEGAL' },
	{ name: 'Serbia', value: 'SERBIA' },
	{ name: 'Seychelles', value: 'SEYCHELLES' },
	{ name: 'Sierra Leone', value: 'SIERRA_LEONE' },
	{ name: 'Singapore', value: 'SINGAPORE' },
	{ name: 'Sint Maarten (Dutch Part)', value: 'SINT_MAARTEN_DUTCH_PART' },
	{ name: 'Slovakia', value: 'SLOVAKIA' },
	{ name: 'Slovenia', value: 'SLOVENIA' },
	{ name: 'Solomon Islands', value: 'SOLOMON_ISLANDS' },
	{ name: 'Somalia', value: 'SOMALIA' },
	{ name: 'South Africa', value: 'SOUTH_AFRICA' },
	{ name: 'South Georgia and the South Sandwich Islands', value: 'SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS' },
	{ name: 'South Sudan', value: 'SOUTH_SUDAN' },
	{ name: 'Spain', value: 'SPAIN' },
	{ name: 'Sri Lanka', value: 'SRI_LANKA' },
	{ name: 'Sudan', value: 'SUDAN' },
	{ name: 'Suriname', value: 'SURINAME' },
	{ name: 'Svalbard and Jan Mayen', value: 'SVALBARD_AND_JAN_MAYEN' },
	{ name: 'Sweden', value: 'SWEDEN' },
	{ name: 'Switzerland', value: 'SWITZERLAND' },
	{ name: 'Syria', value: 'SYRIA' },
	{ name: 'Taiwan', value: 'TAIWAN' },
	{ name: 'Tajikistan', value: 'TAJIKISTAN' },
	{ name: 'Tanzania', value: 'TANZANIA' },
	{ name: 'Thailand', value: 'THAILAND' },
	{ name: 'Timor-Leste', value: 'TIMOR_LESTE' },
	{ name: 'Togo', value: 'TOGO' },
	{ name: 'Tokelau', value: 'TOKELAU' },
	{ name: 'Tonga', value: 'TONGA' },
	{ name: 'Trinidad and Tobago', value: 'TRINIDAD_AND_TOBAGO' },
	{ name: 'Tunisia', value: 'TUNISIA' },
	{ name: 'Turkey', value: 'TURKEY' },
	{ name: 'Turkmenistan', value: 'TURKMENISTAN' },
	{ name: 'Turks and Caicos Islands', value: 'TURKS_AND_CAICOS_ISLANDS' },
	{ name: 'Tuvalu', value: 'TUVALU' },
	{ name: 'Uganda', value: 'UGANDA' },
	{ name: 'Ukraine', value: 'UKRAINE' },
	{ name: 'United Arab Emirates', value: 'UNITED_ARAB_EMIRATES' },
	{ name: 'United Kingdom', value: 'UNITED_KINGDOM' },
	{ name: 'United States', value: 'UNITED_STATES_OF_AMERICA' },
	{ name: 'Uruguay', value: 'URUGUAY' },
	{ name: 'Uzbekistan', value: 'UZBEKISTAN' },
	{ name: 'Vanuatu', value: 'VANUATU' },
	{ name: 'Venezuela', value: 'VENEZUELA' },
	{ name: 'Vietnam', value: 'VIETNAM' },
	{ name: 'Virgin Islands (British)', value: 'VIRGIN_ISLANDS_BRITISH' },
	{ name: 'Virgin Islands (U.S.)', value: 'VIRGIN_ISLANDS_US' },
	{ name: 'Wallis and Futuna', value: 'WALLIS_AND_FUTUNA' },
	{ name: 'Western Sahara', value: 'WESTERN_SAHARA' },
	{ name: 'Yemen', value: 'YEMEN' },
	{ name: 'Zambia', value: 'ZAMBIA' },
	{ name: 'Zimbabwe', value: 'ZIMBABWE' },
];