export const PODCAST_GENRES = [
	{ name: 'Arts', value: 'PODCASTSERIES_ARTS' },
	{ name: 'Arts - Books', value: 'PODCASTSERIES_ARTS_BOOKS' },
	{ name: 'Arts - Design', value: 'PODCASTSERIES_ARTS_DESIGN' },
	{ name: 'Arts - Fashion and Beauty', value: 'PODCASTSERIES_ARTS_FASHION_AND_BEAUTY' },
	{ name: 'Arts - Food', value: 'PODCASTSERIES_ARTS_FOOD' },
	{ name: 'Arts - Performing Arts', value: 'PODCASTSERIES_ARTS_PERFORMING_ARTS' },
	{ name: 'Arts - Visual Arts', value: 'PODCASTSERIES_ARTS_VISUAL_ARTS' },
	{ name: 'Business', value: 'PODCASTSERIES_BUSINESS' },
	{ name: 'Business - Careers', value: 'PODCASTSERIES_BUSINESS_CAREERS' },
	{ name: 'Business - Entrepreneurship', value: 'PODCASTSERIES_BUSINESS_ENTREPRENEURSHIP' },
	{ name: 'Business - Investing', value: 'PODCASTSERIES_BUSINESS_INVESTING' },
	{ name: 'Business - Management', value: 'PODCASTSERIES_BUSINESS_MANAGEMENT' },
	{ name: 'Business - Marketing', value: 'PODCASTSERIES_BUSINESS_MARKETING' },
	{ name: 'Business - Non Profit', value: 'PODCASTSERIES_BUSINESS_NON_PROFIT' },
	{ name: 'Comedy', value: 'PODCASTSERIES_COMEDY' },
	{ name: 'Comedy - Improv', value: 'PODCASTSERIES_COMEDY_IMPROV' },
	{ name: 'Comedy - Interviews', value: 'PODCASTSERIES_COMEDY_INTERVIEWS' },
	{ name: 'Comedy - Stand-Up', value: 'PODCASTSERIES_COMEDY_STANDUP' },
	{ name: 'Education', value: 'PODCASTSERIES_EDUCATION' },
	{ name: 'Education - Courses', value: 'PODCASTSERIES_EDUCATION_COURSES' },
	{ name: 'Education - How To', value: 'PODCASTSERIES_EDUCATION_HOW_TO' },
	{ name: 'Education - Language Learning', value: 'PODCASTSERIES_EDUCATION_LANGUAGE_LEARNING' },
	{ name: 'Education - Self Improvement', value: 'PODCASTSERIES_EDUCATION_SELF_IMPROVEMENT' },
	{ name: 'Fiction', value: 'PODCASTSERIES_FICTION' },
	{ name: 'Fiction - Comedy Fiction', value: 'PODCASTSERIES_FICTION_COMEDY_FICTION' },
	{ name: 'Fiction - Drama', value: 'PODCASTSERIES_FICTION_DRAMA' },
	{ name: 'Fiction - Science Fiction', value: 'PODCASTSERIES_FICTION_SCIENCE_FICTION' },
	{ name: 'Government', value: 'PODCASTSERIES_GOVERNMENT' },
	{ name: 'Health and Fitness', value: 'PODCASTSERIES_HEALTH_AND_FITNESS' },
	{ name: 'Health and Fitness - Alternative Health', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_ALTERNATIVE_HEALTH' },
	{ name: 'Health and Fitness - Fitness', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_FITNESS' },
	{ name: 'Health and Fitness - Medicine', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_MEDICINE' },
	{ name: 'Health and Fitness - Mental Health', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_MENTAL_HEALTH' },
	{ name: 'Health and Fitness - Nutrition', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_NUTRITION' },
	{ name: 'Health and Fitness - Sexuality', value: 'PODCASTSERIES_HEALTH_AND_FITNESS_SEXUALITY' },
	{ name: 'History', value: 'PODCASTSERIES_HISTORY' },
	{ name: 'Kids and Family', value: 'PODCASTSERIES_KIDS_AND_FAMILY' },
	{ name: 'Kids and Family - Education for Kids', value: 'PODCASTSERIES_KIDS_AND_FAMILY_EDUCATION_FOR_KIDS' },
	{ name: 'Kids and Family - Parenting', value: 'PODCASTSERIES_KIDS_AND_FAMILY_PARENTING' },
	{ name: 'Kids and Family - Pets and Animals', value: 'PODCASTSERIES_KIDS_AND_FAMILY_PETS_AND_ANIMALS' },
	{ name: 'Kids and Family - Stories for Kids', value: 'PODCASTSERIES_KIDS_AND_FAMILY_STORIES_FOR_KIDS' },
	{ name: 'Leisure', value: 'PODCASTSERIES_LEISURE' },
	{ name: 'Leisure - Animation and Manga', value: 'PODCASTSERIES_LEISURE_ANIMATION_AND_MANGA' },
	{ name: 'Leisure - Automotive', value: 'PODCASTSERIES_LEISURE_AUTOMOTIVE' },
	{ name: 'Leisure - Aviation', value: 'PODCASTSERIES_LEISURE_AVIATION' },
	{ name: 'Leisure - Crafts', value: 'PODCASTSERIES_LEISURE_CRAFTS' },
	{ name: 'Leisure - Games', value: 'PODCASTSERIES_LEISURE_GAMES' },
	{ name: 'Leisure - Hobbies', value: 'PODCASTSERIES_LEISURE_HOBBIES' },
	{ name: 'Leisure - Home and Garden', value: 'PODCASTSERIES_LEISURE_HOME_AND_GARDEN' },
	{ name: 'Leisure - Video Games', value: 'PODCASTSERIES_LEISURE_VIDEO_GAMES' },
	{ name: 'Music', value: 'PODCASTSERIES_MUSIC' },
	{ name: 'Music - Commentary', value: 'PODCASTSERIES_MUSIC_COMMENTARY' },
	{ name: 'Music - History', value: 'PODCASTSERIES_MUSIC_HISTORY' },
	{ name: 'Music - Interviews', value: 'PODCASTSERIES_MUSIC_INTERVIEWS' },
	{ name: 'News', value: 'PODCASTSERIES_NEWS' },
	{ name: 'News - Business', value: 'PODCASTSERIES_NEWS_BUSINESS' },
	{ name: 'News - Commentary', value: 'PODCASTSERIES_NEWS_COMMENTARY' },
	{ name: 'News - Daily News', value: 'PODCASTSERIES_NEWS_DAILY_NEWS' },
	{ name: 'News - Entertainment', value: 'PODCASTSERIES_NEWS_ENTERTAINMENT' },
	{ name: 'News - Politics', value: 'PODCASTSERIES_NEWS_POLITICS' },
	{ name: 'News - Sports', value: 'PODCASTSERIES_NEWS_SPORTS' },
	{ name: 'News - Tech', value: 'PODCASTSERIES_NEWS_TECH' },
	{ name: 'Religion and Spirituality', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY' },
	{ name: 'Religion and Spirituality - Buddhism', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_BUDDHISM' },
	{ name: 'Religion and Spirituality - Christianity', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_CHRISTIANITY' },
	{ name: 'Religion and Spirituality - Hinduism', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_HINDUISM' },
	{ name: 'Religion and Spirituality - Islam', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_ISLAM' },
	{ name: 'Religion and Spirituality - Judaism', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_JUDAISM' },
	{ name: 'Religion and Spirituality - Religion', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_RELIGION' },
	{ name: 'Religion and Spirituality - Spirituality', value: 'PODCASTSERIES_RELIGION_AND_SPIRITUALITY_SPIRITUALITY' },
	{ name: 'Science', value: 'PODCASTSERIES_SCIENCE' },
	{ name: 'Science - Astronomy', value: 'PODCASTSERIES_SCIENCE_ASTRONOMY' },
	{ name: 'Science - Chemistry', value: 'PODCASTSERIES_SCIENCE_CHEMISTRY' },
	{ name: 'Science - Earth Sciences', value: 'PODCASTSERIES_SCIENCE_EARTH_SCIENCES' },
	{ name: 'Science - Life Sciences', value: 'PODCASTSERIES_SCIENCE_LIFE_SCIENCES' },
	{ name: 'Science - Mathematics', value: 'PODCASTSERIES_SCIENCE_MATHEMATICS' },
	{ name: 'Science - Natural Sciences', value: 'PODCASTSERIES_SCIENCE_NATURAL_SCIENCES' },
	{ name: 'Science - Nature', value: 'PODCASTSERIES_SCIENCE_NATURE' },
	{ name: 'Science - Physics', value: 'PODCASTSERIES_SCIENCE_PHYSICS' },
	{ name: 'Science - Social Sciences', value: 'PODCASTSERIES_SCIENCE_SOCIAL_SCIENCES' },
	{ name: 'Society and Culture', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE' },
	{ name: 'Society and Culture - Documentary', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_DOCUMENTARY' },
	{ name: 'Society and Culture - Personal Journals', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_PERSONAL_JOURNALS' },
	{ name: 'Society and Culture - Philosophy', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_PHILOSOPHY' },
	{ name: 'Society and Culture - Places and Travel', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_PLACES_AND_TRAVEL' },
	{ name: 'Society and Culture - Relationships', value: 'PODCASTSERIES_SOCIETY_AND_CULTURE_RELATIONSHIPS' },
	{ name: 'Sports', value: 'PODCASTSERIES_SPORTS' },
	{ name: 'Sports - Baseball', value: 'PODCASTSERIES_SPORTS_BASEBALL' },
	{ name: 'Sports - Basketball', value: 'PODCASTSERIES_SPORTS_BASKETBALL' },
	{ name: 'Sports - Cricket', value: 'PODCASTSERIES_SPORTS_CRICKET' },
	{ name: 'Sports - Fantasy Sports', value: 'PODCASTSERIES_SPORTS_FANTASY_SPORTS' },
	{ name: 'Sports - Football', value: 'PODCASTSERIES_SPORTS_FOOTBALL' },
	{ name: 'Sports - Golf', value: 'PODCASTSERIES_SPORTS_GOLF' },
	{ name: 'Sports - Hockey', value: 'PODCASTSERIES_SPORTS_HOCKEY' },
	{ name: 'Sports - Rugby', value: 'PODCASTSERIES_SPORTS_RUGBY' },
	{ name: 'Sports - Running', value: 'PODCASTSERIES_SPORTS_RUNNING' },
	{ name: 'Sports - Soccer', value: 'PODCASTSERIES_SPORTS_SOCCER' },
	{ name: 'Sports - Swimming', value: 'PODCASTSERIES_SPORTS_SWIMMING' },
	{ name: 'Sports - Tennis', value: 'PODCASTSERIES_SPORTS_TENNIS' },
	{ name: 'Sports - Volleyball', value: 'PODCASTSERIES_SPORTS_VOLLEYBALL' },
	{ name: 'Sports - Wilderness', value: 'PODCASTSERIES_SPORTS_WILDERNESS' },
	{ name: 'Sports - Wrestling', value: 'PODCASTSERIES_SPORTS_WRESTLING' },
	{ name: 'Technology', value: 'PODCASTSERIES_TECHNOLOGY' },
	{ name: 'True Crime', value: 'PODCASTSERIES_TRUE_CRIME' },
	{ name: 'TV and Film', value: 'PODCASTSERIES_TV_AND_FILM' },
	{ name: 'TV and Film - After Shows', value: 'PODCASTSERIES_TV_AND_FILM_AFTER_SHOWS' },
	{ name: 'TV and Film - Film Reviews', value: 'PODCASTSERIES_TV_AND_FILM_FILM_REVIEWS' },
	{ name: 'TV and Film - History', value: 'PODCASTSERIES_TV_AND_FILM_HISTORY' },
	{ name: 'TV and Film - Interviews', value: 'PODCASTSERIES_TV_AND_FILM_INTERVIEWS' },
	{ name: 'TV and Film - TV Reviews', value: 'PODCASTSERIES_TV_AND_FILM_TV_REVIEWS' },
];